// Shared French word-list helpers. The raw blobs live in ./common and ./extended
// (generated by scripts/build-words.mjs); import only the tier(s) a game needs —
// this module stays blob-free so helpers never drag a list into a bundle.

export const parseWords = (raw: string): string[] => raw.trim().split(/\s+/);

export const byLength = (list: string[], min: number, max: number): string[] =>
	list.filter((w) => w.length >= min && w.length <= max);

/** Merge two sorted, disjoint lists into one sorted array. */
export function mergeSorted(a: string[], b: string[]): string[] {
	const out: string[] = [];
	let i = 0, j = 0;
	while (i < a.length && j < b.length) out.push(a[i] < b[j] ? a[i++] : b[j++]);
	while (i < a.length) out.push(a[i++]);
	while (j < b.length) out.push(b[j++]);
	return out;
}

/** Index of the first entry >= prefix (lower bound). */
const lowerBound = (sorted: string[], s: string): number => {
	let lo = 0, hi = sorted.length;
	while (lo < hi) {
		const mid = (lo + hi) >> 1;
		if (sorted[mid] < s) lo = mid + 1;
		else hi = mid;
	}
	return lo;
};

export const hasPrefix = (sorted: string[], prefix: string): boolean => {
	const i = lowerBound(sorted, prefix);
	return i < sorted.length && sorted[i].startsWith(prefix);
};

export const hasWord = (sorted: string[], w: string): boolean => {
	const i = lowerBound(sorted, w);
	return i < sorted.length && sorted[i] === w;
};

export function letterCounts(word: string): Map<string, number> {
	const m = new Map<string, number>();
	for (const ch of word) m.set(ch, (m.get(ch) ?? 0) + 1);
	return m;
}

/** Multiset containment: can `word` be formed from `base` letters (each used once)? */
export function isSubset(word: string, base: Map<string, number>): boolean {
	const used = new Map<string, number>();
	for (const ch of word) {
		const u = (used.get(ch) ?? 0) + 1;
		if (u > (base.get(ch) ?? 0)) return false;
		used.set(ch, u);
	}
	return true;
}
