import { chromium } from 'playwright';
import { startServer } from './preview-server.mjs';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const OUT = process.argv[2];
const server = await startServer(4391);
const browser = await chromium.launch({ args: ['--enable-unsafe-swiftshader', '--use-gl=angle'] });
const ctx = await browser.newContext({ locale: 'fr-FR', viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
await page.goto(`${server.base}/jeux/petanque/`, { waitUntil: 'networkidle' });
await page.waitForSelector('.pe-canvas');
try { await page.locator('.tuto-close').click({ timeout: 2500 }); } catch {}
await page.waitForFunction(() => window.__petanque && window.__petanque().status === 'aim', null, { timeout: 15000 });
await page.getByRole('tab', { name: /Libre/ }).click();
await sleep(700);
await page.locator('.pe-ground .pe-bar-x').click();
await page.evaluate(() => { document.querySelector('.game-page')?.classList.add('gf-full'); document.documentElement.classList.add('gf-full'); window.dispatchEvent(new Event('resize')); });
await sleep(1400);
await page.waitForFunction(() => window.__petanque().view === 'dessus', null, { timeout: 8000 }).catch(() => {});
let box = await page.locator('.pe-canvas').boundingBox();
await page.mouse.click(box.x + box.width / 2, box.y + box.height * 0.42);
await sleep(400);
await page.getByRole('button', { name: /Lancer le bouchon/ }).click({ timeout: 6000 });
await page.waitForFunction(() => window.__petanque().status === 'rolling', null, { timeout: 8000 });
await page.waitForFunction(() => window.__petanque().status !== 'rolling', null, { timeout: 40000 });
await page.waitForFunction(() => !window.__petanque().intro, null, { timeout: 9000 }).catch(() => {});
await sleep(1200);
await page.getByRole('button', { name: /Mode expert/ }).click();
await sleep(300);
box = await page.locator('.pe-canvas').boundingBox();
const arm = (await page.evaluate(() => window.__petanque())).arm;
for (const [name, f] of [['left', 0.08], ['centre', 0.5], ['right', 0.92]]) {
	const px = box.x + arm.left + arm.width * f, py = box.y + arm.cy;
	await page.mouse.move(px, py);
	await page.mouse.down();
	await page.mouse.move(px, box.y + arm.top - 150, { steps: 12 });
	await sleep(700);
	await page.screenshot({ path: `${OUT}/effet-${name}.png` });
	await page.mouse.move(px, py, { steps: 4 });
	await sleep(150);
	await page.mouse.up();
	await sleep(400);
}
console.log('errors:', errs.length ? errs : 'none');
await browser.close();
server.close?.();
process.exit(0);
