// Pre-generate every Tectonique grid. Run with `npm run grids:tectonique`.
//
// Solving a 6×6 board takes ~0.5 s here and several seconds on a phone, so the puzzles
// cannot be generated in the browser. They are built once, offline, each with the exact
// optimal move count the star thresholds and the "record" hint are based on — which also
// guarantees every shipped grid is solvable.
//
// Deterministic: same master seeds in, same file out.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { mulberry32 } from '../src/games/prng';
import { encodeBoard, findBoard, type GenParams } from '../src/games/tectonique/engine';

interface Band {
	from: number; // first level of the band (levels only)
	params: GenParams;
	minOpt: number;
	maxOpt: number;
}

// Windows are centred on each setup's measured optimum mode, so a board rarely gets
// rejected — one BFS per candidate is by far the expensive part.
const LEVEL_BANDS: Band[] = [
	{ from: 1, params: { n: 4, crystals: 2, rowLocks: 1, colLocks: 0 }, minOpt: 2, maxOpt: 4 },
	{ from: 15, params: { n: 4, crystals: 3, rowLocks: 1, colLocks: 1 }, minOpt: 3, maxOpt: 5 },
	{ from: 29, params: { n: 5, crystals: 3, rowLocks: 1, colLocks: 1 }, minOpt: 4, maxOpt: 6 },
	{ from: 47, params: { n: 5, crystals: 4, rowLocks: 2, colLocks: 1 }, minOpt: 5, maxOpt: 7 },
	{ from: 65, params: { n: 5, crystals: 4, rowLocks: 2, colLocks: 2 }, minOpt: 6, maxOpt: 8 },
	{ from: 81, params: { n: 6, crystals: 4, rowLocks: 2, colLocks: 2 }, minOpt: 6, maxOpt: 9 },
	{ from: 91, params: { n: 6, crystals: 5, rowLocks: 2, colLocks: 2 }, minOpt: 7, maxOpt: 8 },
];

// One pool per daily difficulty index (0 = start of week, 2 = week-end).
const DAILY_BANDS: Omit<Band, 'from'>[] = [
	{ params: { n: 5, crystals: 3, rowLocks: 1, colLocks: 1 }, minOpt: 4, maxOpt: 6 },
	{ params: { n: 5, crystals: 4, rowLocks: 2, colLocks: 2 }, minOpt: 5, maxOpt: 8 },
	{ params: { n: 6, crystals: 4, rowLocks: 2, colLocks: 2 }, minOpt: 6, maxOpt: 9 },
];

const DAILY_PER_BAND = 150;
const LEVEL_COUNT = 100;

const bandFor = (level: number): Band =>
	[...LEVEL_BANDS].reverse().find((b) => level >= b.from) ?? LEVEL_BANDS[0];

interface Packed {
	n: number;
	cells: string;
	opt: number;
}

const make = (rng: () => number, b: Omit<Band, 'from'>, what: string): Packed => {
	const got = findBoard(rng, b.params, b.minOpt, b.maxOpt, 4000);
	if (!got) throw new Error(`no board for ${what} (${JSON.stringify(b)})`);
	return { n: got.board.n, cells: encodeBoard(got.board), opt: got.opt };
};

const t0 = Date.now();

const levels: Packed[] = [];
for (let l = 1; l <= LEVEL_COUNT; l++) {
	const band = bandFor(l);
	// Per-level seed: regenerating one band never disturbs the others.
	levels.push(make(mulberry32((Math.imul(l, 22695477) ^ 0x1b56c4e9) >>> 0), band, `level ${l}`));
	if (l % 10 === 0) console.log(`level ${l}/${LEVEL_COUNT}  ${((Date.now() - t0) / 1000).toFixed(0)}s`);
}

const daily: Packed[][] = [];
for (let d = 0; d < DAILY_BANDS.length; d++) {
	const rng = mulberry32((Math.imul(d + 1, 2654435761) ^ 0x5bf03635) >>> 0);
	const pool: Packed[] = [];
	for (let i = 0; i < DAILY_PER_BAND; i++) pool.push(make(rng, DAILY_BANDS[d], `daily ${d}/${i}`));
	daily.push(pool);
	console.log(`daily band ${d}: ${pool.length} grids  ${((Date.now() - t0) / 1000).toFixed(0)}s`);
}

const row = (p: Packed): string => `\t{ n: ${p.n}, cells: '${p.cells}', opt: ${p.opt} },`;
const optSpread = (list: Packed[]): string => {
	const h = new Map<number, number>();
	for (const p of list) h.set(p.opt, (h.get(p.opt) ?? 0) + 1);
	return [...h.keys()].sort((a, b) => a - b).map((k) => `${k}:${h.get(k)}`).join(' ');
};

const out = `// GENERATED by scripts/generate-tectonique.mts — do not edit by hand.
// \`opt\` is the proven fewest number of moves (BFS over the whole reachable state space),
// so it doubles as the 3★ threshold and as the "record" shown to the player.
//
// levels: optimum spread ${optSpread(levels)}
// daily:  ${daily.map((p, i) => `band ${i} → ${optSpread(p)}`).join('  |  ')}

export interface PackedGrid {
\tn: number;
\tcells: string;
\topt: number;
}

/** Index 0 = level 1. */
export const TECTONIQUE_LEVELS: PackedGrid[] = [
${levels.map(row).join('\n')}
];

/** One pool per daily difficulty index (0 easiest → 2 hardest). */
export const TECTONIQUE_DAILY: PackedGrid[][] = [
${daily.map((pool) => `\t[\n${pool.map((p) => `\t${row(p)}`).join('\n')}\n\t],`).join('\n')}
];
`;

const dest = fileURLToPath(new URL('../src/games/tectonique/grids.ts', import.meta.url));
writeFileSync(dest, out, 'utf8');
console.log(`\nwrote ${dest}\nlevels ${levels.length}  daily ${daily.map((p) => p.length).join('/')}  in ${((Date.now() - t0) / 1000).toFixed(0)}s`);
